Auto update component star counts using a Github action
svelte-society/sveltesociety.dev-legacy pull request #146
Opened 2021-01-25 01:05 UTC by mikeesto

This PR uses a GitHub action to update the star count of every component once a day. Closes https://github.com/svelte-society/sveltesociety.dev/issues/94 . Currently only works for components hosted on GitHub, although almost all of them are.  I wasn't sure where the best place was to put `update-stars.js` ? Thanks!

2021-01-25 07:46 UTC, kevmodrome commented
This is great! I think we can put the file in a `scripts ` folder in the root.

2021-01-29 16:04 UTC, HAUDRAUFHAUN requested changes
LGTM! Please make sure to change the requested fix, then it's fine I think.

2021-01-29 16:04 UTC, HAUDRAUFHAUN commented on scripts/update-stars.js
> +const pathToData = path.resolve("./src/pages/components/components.json");
please use the `@/` alias instead of `./src/`

2021-01-30 05:10 UTC, mikeesto commented on scripts/update-stars.js
> +const pathToData = path.resolve("./src/pages/components/components.json");
Hi @HAUDRAUFHAUN . Happy to change this but I can't get it to work - see below where I tried to run in a test repository. Perhaps I misunderstood what you meant?

`const pathToData = path.resolve("@/pages/components/components.json");`

`Error: ENOENT: no such file or directory, open '/home/runner/work/svelte-store-test/svelte-store-test/@/pages/components/components.json'`

2021-01-30 07:55 UTC, HAUDRAUFHAUN commented on scripts/update-stars.js
> +const pathToData = path.resolve("./src/pages/components/components.json");
This is weird 🤔. I think the alias maybe only works with importing the data, my fault 😅

2021-01-30 07:58 UTC, HAUDRAUFHAUN commented on scripts/update-stars.js
> +const pathToData = path.resolve("./src/pages/components/components.json");
But however you have to change the to the json file, because you moved the update stars to scripts...

2021-01-30 08:11 UTC, mikeesto commented on scripts/update-stars.js
> +const pathToData = path.resolve("./src/pages/components/components.json");
The working directory of the action is the root - it's not relative to where `update-stars.js` is

2021-01-30 16:10 UTC, HAUDRAUFHAUN commented on scripts/update-stars.js
> +const pathToData = path.resolve("./src/pages/components/components.json");
Ok thanks

2021-01-30 16:12 UTC, HAUDRAUFHAUN approved these changes
LGTM 👍🏼

2021-01-30 16:14 UTC, HAUDRAUFHAUN commented
I'll let @kevmodrome to final merge this because I don't now if I have access to controll the actions. Great work @mikeesto 😃

2021-01-31 08:02 UTC, merged