fix: class bindings
svelte-society/sveltesociety.dev-legacy pull request #164
Opened 2021-02-06 10:20 UTC by madacol

The class that was actually being added was `true` instead of the intended `active`

2021-02-06 10:25 UTC, HAUDRAUFHAUN commented
Please use the `staging` branch for your PR's in the future

2021-02-06 10:42 UTC, kevmodrome requested changes

2021-02-06 10:42 UTC, kevmodrome commented on src/pages/cheatsheet/cheat-sheet.js
> +<div class={active ? 'active' : ''}  class={type}>
this should be `class:active` rather than the proposed or old implementation. If that can be fixed we can have this merged! :)

2021-02-06 15:28 UTC, madacol commented on src/pages/cheatsheet/cheat-sheet.js
> +<div class={active ? 'active' : ''}  class={type}>
I'm not sure I understand what you mean.
The code is showing different forms to assign classes, `class={...}`, `class:active={...}`, and `class:active`.
Maybe you want the `class={...}` example to be removed?

2021-02-08 18:48 UTC, kevmodrome commented on src/pages/cheatsheet/cheat-sheet.js
> +<div class={active ? 'active' : ''}  class={type}>
Ohhhhh, I mistakenly thought it was inside of some component. Did not realise it was in the cheat-sheet. My bad!

2021-02-08 18:49 UTC, kevmodrome approved these changes

2021-02-08 18:49 UTC, merged

2021-02-08 18:49 UTC, kevmodrome commented
Thanks for the PR!