Added Sveltefire
svelte-society/sveltesociety.dev-legacy pull request #200
Opened 2021-03-24 17:09 UTC by lguzzon

See you on SvelteSociety site ...

2021-03-24 17:42 UTC, kevmodrome requested changes, later dismissed
Please remove the firebase tag! 👍

2021-03-25 10:15 UTC, lguzzon commented
> Please remove the firebase tag! 👍

Done!!! 👌

2021-03-25 10:40 UTC, stephane-vanraes commented
it could use the tag `stores and state` though ?

and _maybe_ we could introduce a `cloudservices` tag ? what do you think @kevmodrome ?

2021-04-05 18:46 UTC, kevmodrome commented
@stephane-vanraes sounds good! Completely missed this :(

2021-04-30 19:23 UTC, MacFJA requested changes, later dismissed

2021-04-30 19:23 UTC, MacFJA commented on src/pages/components/components.json
> +    "npm": "https://www.npmjs.com/package/sveltefire",
This should be the NPM package name, not the URL to the NPM page
```suggestion
    "npm": "sveltefire",
```

2021-06-07 07:26 UTC, stephane-vanraes approved these changes

2021-06-07 07:29 UTC, stephane-vanraes approved these changes

2021-06-08 07:46 UTC, merged