Update components.json
svelte-society/sveltesociety.dev-legacy pull request #215
Opened 2021-04-29 15:05 UTC by arthurgermano

Added SCR - Svelte Client Router

2021-04-30 19:21 UTC, MacFJA requested changes

2021-04-30 19:21 UTC, MacFJA commented on src/pages/components/components.json
> +    "npm": "https://www.npmjs.com/package/svelte-client-router",
This should be only the NPM package name, not the NPM URL
```suggestion
    "npm": "svelte-client-router",
```

2021-04-30 19:21 UTC, MacFJA commented on src/pages/components/components.json
> +      "routing"
The tags `router`, `spa`, `routes`, `routing` doesn't exists (yet?)

The existing tags that are close to yours are:
 - `routers`

----

For me the tag `spa` can be added, but for the others I'm not sure they add any "improvements".

2021-04-30 19:21 UTC, MacFJA commented on src/pages/components/components.json
> +    "category": "Router and SPA"
The category **`Router and SPA`** does not exists.
The closest are **`Routers`** or _Empty_ (<=> **Unclassified**)

2021-04-30 19:43 UTC, arthurgermano reviewed
Fixed Issues

2021-04-30 19:44 UTC, arthurgermano commented on src/pages/components/components.json
> +      "routing"
Updated to only routers and npm from link to name

2021-04-30 19:44 UTC, arthurgermano commented on src/pages/components/components.json
> +    "category": "Router and SPA"
Updated to routers categories only

2021-04-30 20:02 UTC, MacFJA requested changes

2021-04-30 20:02 UTC, MacFJA commented on src/pages/components/components.json
> +    "title: SCR Svelte Client Router",
There are missing quotes (`"`) here
```suggestion
    "title": "SCR Svelte Client Router",
```

2021-04-30 20:19 UTC, arthurgermano reviewed
Fixed problem with title

2021-04-30 20:19 UTC, MacFJA approved these changes

2021-05-02 16:02 UTC, kevmodrome approved these changes

2021-05-02 16:02 UTC, merged