Added @cloudedots/svelte-forms library to components
svelte-society/sveltesociety.dev-legacy pull request #217
Opened 2021-04-30 16:41 UTC by DhyeyMoliya

Added [@cloudedots/svelte-forms](https://github.com/cloudedots-projects/svelte-forms) library to components. A Svelte Forms Library with Validation.

2021-04-30 19:11 UTC, MacFJA requested changes

2021-04-30 19:11 UTC, MacFJA commented on src/pages/components/components.json
> +    "npm": "https://www.npmjs.com/package/@cloudedots/svelte-forms",
This should be only the NPM package name, not an URL to NPM
```suggestion
    "npm": "@cloudedots/svelte-forms",
```

2021-04-30 19:52 UTC, benmccann commented on src/pages/components/components.json
> +      "form",
I left the same comment over in https://github.com/sveltejs/community/pull/444/files#r624150304 but maybe we can combine the `form` and `forms` tags so that we don't have duplicates? Don't ask me why there are two repos for this :stuck_out_tongue_closed_eyes:

2021-05-01 01:27 UTC, DhyeyMoliya commented on src/pages/components/components.json
> +      "form",
Removed similar tags

2021-05-01 01:29 UTC, DhyeyMoliya commented on src/pages/components/components.json
> +    "npm": "https://www.npmjs.com/package/@cloudedots/svelte-forms",
Done.

2021-05-01 08:49 UTC, MacFJA approved these changes

2021-05-31 12:49 UTC, stephane-vanraes approved these changes

2021-05-31 12:50 UTC, merged