working recipes section
svelte-society/sveltesociety.dev-legacy pull request #7
Opened 2020-04-10 19:23 UTC by sw-yx

just made a start for now - we need to figure out the data pipelining from markdown to routify (https://github.com/sveltech/routify/issues/149) 

and i couldnt get the blockquotes css to look nice

![image](https://user-images.githubusercontent.com/6764957/79017406-d0baa500-7ba3-11ea-8890-e3d885d77bda.png)

2020-04-11 07:09 UTC, kevmodrome requested changes
Nice! Only one small nit-pick I suppose.

2020-04-11 07:09 UTC, kevmodrome commented on src/pages/recipes/index.svelte
> +<RecipesPage />
I think we're better off sticking the content of the RecipesPage in the actual page here, otherwise it will just be empty

2020-04-11 07:10 UTC, kevmodrome commented on src/pages/recipes/index.svelte
> +<RecipesPage />
On second thought. I think we can actually put most of the sidebar in a _layout.svelte file in the same folder. And then the actual markdown in the index.svelte file.

2020-04-11 14:42 UTC, sw-yx commented on src/pages/recipes/index.svelte
> +<RecipesPage />
the reason i avoided doing those 2 things (putting RecipesPage in there and using `_layout.svelte`) is because we need to share state AND data between the sidebar and the main page, as well as reuse the main page in order to get around Routify's limitations with `[slug]`s.

its not static content - we have to reuse the data.

anyway, Jakob gave us the "proper" way to pull data in https://github.com/sveltech/routify/issues/149 so I need to investigate how to incorporate this. will get to this next week.

2020-04-19 16:53 UTC, kevmodrome commented on src/pages/recipes/index.svelte
> +<RecipesPage />
Crap, got side-tracked and forgot to reply to this, sorry. All right sounds good.

2020-04-19 16:53 UTC, kevmodrome approved these changes

2020-04-19 16:53 UTC, merged