Condense recipe index whitespace
svelte-society/sveltesociety.dev-legacy pull request #77
Opened 2020-09-25 20:05 UTC by zygen

I made this change to make the page more easily readable on smaller screens such as my laptop. It's unsolicited, so please let loose with the criticism =)

Changes include:
- Use rem instead of px measurements in css
- Try to make vertical margins visually similar
- Remove a bunch of extra padding that hid content on smaller screens

The code is formatted with prettier so some unrelated stuff was reformatted.  Sorry about that!

Top:
![Screen Shot 2020-09-25 at 12 22 57](https://user-images.githubusercontent.com/55800/94311006-61f1be00-ff2f-11ea-8971-efe089ab2058.png)

Category Block:
![Screen Shot 2020-09-25 at 12 24 49](https://user-images.githubusercontent.com/55800/94311021-674f0880-ff2f-11ea-8e2f-e1f20727135f.png)

Bottom:
![Screen Shot 2020-09-25 at 12 23 57](https://user-images.githubusercontent.com/55800/94311028-6ae28f80-ff2f-11ea-9467-fbb8b3b08afa.png)

2020-09-25 22:45 UTC, sw-yx requested changes

2020-09-25 22:45 UTC, sw-yx commented on src/components/recipes/CategoryTree.svelte
>  <style>
you seem to have 4 spaces configured for your prettier setting. as a general rule try not to reformat unrelated code in your OSS PR's.

2020-09-25 22:45 UTC, sw-yx commented on src/components/recipes/CategoryTree.svelte
> +    }
added random spaces?

2020-09-25 22:45 UTC, sw-yx commented on src/components/recipes/CategoryTree.svelte
> +    {/each}
unncessary

2020-09-25 22:45 UTC, sw-yx commented on src/pages/recipes/index.svx
>  </script>
unnecessary

2020-09-26 00:19 UTC, zygen commented on src/components/recipes/CategoryTree.svelte
>  <style>
Yeah, these files have inconsistent spacing (2 and 4), so I picked one arbitrarily.  I suppose I should've left it at 2, since that's the default.  Since there doesn't seem to be a standard in this project right now I'll just disable the autoformatter for this project, revert the extraneous changes, and we can talk about it in an issue/discord.

2020-09-26 07:57 UTC, sw-yx approved these changes

2020-09-26 07:57 UTC, merged

2020-09-26 07:57 UTC, sw-yx commented
super awesome, thank you for this!